// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxfa1cDdBluijYKS_nXpvgHNMUlphmcDg',
    appId: '1:488084410469:web:2a88d135b5897a7e45f68c',
    messagingSenderId: '488084410469',
    projectId: 'fir-authentication-ass',
    authDomain: 'fir-authentication-ass.firebaseapp.com',
    storageBucket: 'fir-authentication-ass.firebasestorage.app',
    measurementId: 'G-L17CQK9JS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_YaJ2gDLzDev2M9WgeaqhmYabKh7_qc',
    appId: '1:488084410469:android:cd792e70c651429045f68c',
    messagingSenderId: '488084410469',
    projectId: 'fir-authentication-ass',
    storageBucket: 'fir-authentication-ass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkMnYEaPO5ZZgvctsdHmgOSFU_Sh2P1_M',
    appId: '1:488084410469:ios:87c7ac4e4d3bc39445f68c',
    messagingSenderId: '488084410469',
    projectId: 'fir-authentication-ass',
    storageBucket: 'fir-authentication-ass.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkMnYEaPO5ZZgvctsdHmgOSFU_Sh2P1_M',
    appId: '1:488084410469:ios:87c7ac4e4d3bc39445f68c',
    messagingSenderId: '488084410469',
    projectId: 'fir-authentication-ass',
    storageBucket: 'fir-authentication-ass.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxfa1cDdBluijYKS_nXpvgHNMUlphmcDg',
    appId: '1:488084410469:web:afb9944ff2db22f245f68c',
    messagingSenderId: '488084410469',
    projectId: 'fir-authentication-ass',
    authDomain: 'fir-authentication-ass.firebaseapp.com',
    storageBucket: 'fir-authentication-ass.firebasestorage.app',
    measurementId: 'G-MYWC3DSB0K',
  );
}
